name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./Practice_Project
        run: npm install

      - name: Lint
        working-directory: ./Practice_Project
        run: npm run lint

      - name: Test code
        working-directory: ./Practice_Project
        run: npm test

      - name: Build code
        working-directory: ./Practice_Project
        run: npm run build

      - name: Deploy code
        run: echo "Deploying..."
