name: Lint, Test, and Deploy

on:
  push:
    branches:
      - main  # or any branch you prefer

jobs:
  # Job 1: Lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  # Job 2: Test
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  # Job 3: Build (and Deploy)
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Insert your deploy steps here"