name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm.cmd ci
      - name: Lint
        run: npm.cmd run lint
      - name: Test code
        run: npm.cmd run test
      - name: Build code
        run: npm.cmd run build
      - name: Deploy code
        run: echo "Deploying..."
