name: Issue Events

on:
  issues:
    types: [opened, edited, closed]  # or any issue event types you want to capture

jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Event Details
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
